name: stylus

on: push

jobs:
  check:
    strategy:
      fail-fast: true

    name: Check contracts and ABIs 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-aarch64-unknown-linux-gnu
          targets: wasm32-unknown-unknown
        id: rust

      - name: Install Stylus CLI
        run: |
          RUSTFLAGS="-C link-args=-rdynamic" cargo install --force cargo-stylus
          rustup component add rust-src --toolchain nightly-aarch64-unknown-linux-gnu
        id: stylus

      - name: Check project is valid
        run: |
          cargo stylus check
        id: check
      
      - name: Check ABIs can be generated
        run: |
          cargo stylus export-abi
        id: abi